theme: jekyll-theme-minimal
title: Jonathan Zhu
description: Biology and Mathematics
logo: assets/images/JonZhu.png
show_downloads: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


# Permalinks
permalink:        pretty

