theme: jekyll-theme-minimal
title: Jonathan Zhu
description: M.S., Computational Biology, Carnegie Mellon University
logo: assets/images/JonZhu.png
show_downloads: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

paginate:         5

# Permalinks
permalink:        pretty

